LICENSE
README.md
package-lock.json
package.json

-     Add LICENSE file to package copying it from the root folder
-     Create or update the README file
-     Check package.json to update information (homepage, author, license, description)
-     Check package.json to update dependencies
-     Check package.json to update scripts

[EX-3937] update files

---

package-lock.json
src/components/facets/facets.vue

The aim of this PR is import and fix the SlicedFilters in the facets.vue.
Motivation and Context
SlicedFilters was not imported in the facets.vue component so it was not warking.
SlicedFitlers didn't receive filters as property.
Check that the SlicedFilter works properly.

feat(facets): Fix SlicedFilters filters input in facets.vue

---

package-lock.json

chore(build): fix depedencies

---

src/components/layout.vue
src/components/results/index.ts
src/x-components/adapter.ts
tsconfig.json

chore(build): fix result import inside the app.vue

---

src/adapter/adapter.ts
src/adapter/demo-request-mapper.ts

EX-4142
This PR fixes the issue with the related tags when one of them is clicked.

fix(adapter): replace search request class mapper 

---

src/adapter/adapter.ts

feat(recommendations): configure recommendations endpoint in the adapter

---

src/adapter/adapter.ts

fix(adapter): update spellcheck responsePaths

---

src/adapter/adapter.ts
src/adapter/demo-request-filters.mapper.ts

feat(facets): add request mapper for HierarchicalFilters

---

package-lock.json
package.json
src/App.vue
src/components/main.vue

EX-4219
This PR updates `XComponents` and uses the new `BaseIdTogglePanelButton`

Update layout with base id toggle panel button

---

package-lock.json
package.json
src/App.vue
src/components/main.vue

EX-4302
Add an ` v-if="$x.device === 'desktop'"` in the view template and validate the change.

components(device): Add new `DeviceDetector` component in the main view

---

package-lock.json
package.json

Update x-translations dependency

---

package-lock.json
package.json
src/App.vue
src/components/main.vue

To test this, you have to use the build of this pr:
[https://github.com/empathyco/x/pull/96](PR)
Change the xcomponents dependency to use that local build. When you have it, you can test that right now you can open X using the API:
X.search() or X.search('dress')
EX-3555

feat: change BaseIdModal to use BaseEventsModal

---

docs/i18n.md
src/App.vue
src/vue.d.ts
src/x-components/plugin.options.ts

To test it, you can open the server and open the console. There, you can type:
window.initX.lang = "es"
window.initX.searchLang = "es"
EX-4120

feat: add hot swap for the lang and the searchLang

---

src/App.vue
src/i18n/i18n.plugin.ts
src/i18n/i18n.types.ts
src/i18n/messages.types.ts
src/i18n/messages/es.messages.json
src/vue.d.ts
src/x-components/plugin.options.ts

fix(i18n): fix i18n not working with device detector

---

src/adapter/adapter.ts
src/components/env-selector.vue

This updates the RTs endpoint and fix the problem where the extraParams selector doesnt change the environment.
EX-4743

feat(related-tags): update endpoint

---

package-lock.json
package.json

build: Update x-components dependency to 3.0.0-alpha.29.

---

package-lock.json
package.json

build: update version to release.

---

package-lock.json
package.json
public/snippet-script.js
src/adapter/adapter.ts
src/adapter/empathy-endpoints.service.ts
src/components/mobile/mobile.vue
src/components/results/result.vue
src/components/results/results.vue
src/components/scroll-to-top.vue

feat(scroll): Updated scroll components with the latests Scroll XModule

---

README.md
docs/i18n.md
docs/index.md

docs: Link Interface X Components doc

---

package-lock.json
package.json
src/adapter/adapter.ts
src/adapter/demo-result.mapper.ts
src/components/predictive-layer.vue
src/x-components/plugin.options.ts

EX-4517
[Designs](https://www.sketch.com/s/ad08dbbd-2b80-4792-80bb-aff1e1de8ec2/a/zx30ZEa)

feat(sku): add new commponent and styles

---

package-lock.json
package.json
public/snippet-script.js
src/App.vue
src/adapter/adapter.ts

feat(tagging): Add tagging component 

---

package-lock.json
package.json
src/components/related-tags.vue

EX-5080
http://localhost:8080/?query=jeans

feat(related-tags): add curated

---

package.json
src/components/desktop/desktop.vue
src/components/main.vue
src/components/mobile/mobile-toolbar.vue
src/components/mobile/mobile.vue
src/components/predictive-layer.vue
src/components/results/recommendations.vue

EX-5092
This PR is to add the new `LocationProvider` component to the Archetype.
Also, the structure of the components was refactored a little bit to eliminate repetition.
The idea is to have the default locations configured and ready for the query tagging, and for future results events tagging.
Executed a search from each different components, and see the tagging call in the devtools with the right `feature:location`

feat(tagging): Add LocationProvider component.

---

package-lock.json
package.json

[EX-3540](https://searchbroker.atlassian.net/browse/EX-3540)

feat(url): set origin when navigating

---

package-lock.json
package.json
src/App.vue
src/adapter/adapter.ts
src/components/main.vue

EX-5126
Updates X Components version to have last tagging features like tracking the query.
- Topclicked and SKU results do not have a `tagging` property.

feat: Update x-components version to v3.0.0-alpha.35

---

package-lock.json
package.json
src/components/main.vue

EX-5164
Updated to latest alpha version to have the location in the result click

feat(tagging): Add location to result tagging.

---

package-lock.json
package.json
src/adapter/adapter.ts
src/adapter/empathy-endpoints.service.ts

In order to test this PR you need to made a build in the mono repo, add the following code in the package.json, and install dependencies:
```json
"install:local": "npm install file:../../x/packages/x-components/empathyco-x-components-3.0.0-alpha.39.tgz file:../../x/packages/search-adapter/empathyco-x-adapter-7.0.0-alpha.8.tgz file:../../x/packages/search-types/empathyco-x-types-10.0.0-alpha.13.tgz --no-save",
```
EX-5198

feat(next-queries): update endpoint

---

src/adapter/empathy-endpoints.service.ts
src/components/mobile/mobile.vue

[EX-5286](https://searchbroker.atlassian.net/browse/EX-5286)
Update of the related tags and next queries endpoints to use the `beacon-api` endpoint regardless of environment.
Tests have been done by searching a query and checking in the network tab if the request was made to the updated endpoint. The query `shorts` should give related tags and next queries in both environments.

chore(endpoints): update rt & nq endpoint to beacon-api

---

package-lock.json
package.json
src/components/search/related-tags.vue

This upgrades the x-components version and uses the curated icon for the curated related tags. EX-5353

feat(related-tags): customize curated RTs

---

package-lock.json
package.json

Just updates the package version for the staging release

chore: Update package version

---

src/components/results/result.vue
tests/e2e/cucumber/common-steps.spec.ts
tests/e2e/cucumber/mocked-responses.spec.ts
tests/e2e/cucumber/multiple-interactions.feature
tests/e2e/cucumber/multiple-interactions.spec.ts
tests/e2e/cucumber/predictive-components.spec.ts
tests/e2e/cucumber/scroll.feature
tests/e2e/cucumber/scroll.spec.ts
tests/e2e/cucumber/tagging.feature
tests/e2e/cucumber/tagging.spec.ts
tests/e2e/cucumber/url.feature
tests/e2e/cucumber/url.spec.ts
tests/e2e/fixtures/search-response-with-known-results.json
tests/e2e/specs/search-input.spec.ts

After adding first round of smoke test to the archetype, this second one includes:
- Infinite scroll
- URL Navigation
- Multiple consecutive searches.
- Tagging
Since Extra params and Tracking E2E tests are not ready in the X-Components project yet, they were not added now and will be once they are available in X-Components project.
In orden to run the tests independently, please change `cypress.json` `testFiles` parameter to the following:
`"testFiles": "**/*.feature",`

[EX-5272] Add more smoke tests

---

src/adapter/empathy-endpoints.service.ts

EX-5415
Fix NQ and RT endpoints
Set the correct path for endpoints
The motivation is not to use VPN for these endpoints in Staging and Pro

fix(adapter): update `next queries` and `related tags` endpoints in `staging` and `production`

---

src/components/predictive-layer.vue
src/components/search/results/next-queries-group.vue

feat(next-queries): add curated icon

---

package-lock.json
package.json
src/App.vue
src/components/x-modal.vue

EX-6279
Updates Empathy dependencies to its last version.

feat: update empathy dependencies

---

src/components/predictive-layer.vue

feat: config predictive layer

---

src/components/search-box.vue
src/design-system/tokens.scss
tests/e2e/support/index.ts

feat: update search box style and config

---

src/App.vue
src/components/desktop/desktop.vue

feat: show predictive layer over content

---

package-lock.json
package.json
src/components/predictive-layer/predictive-layer.vue

feat(identifier-results): set max items to render to 5

---

src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json

EX-64762
Change texts to improve and complete identifier results in spanish

feature: improve static texts

---

src/components/desktop/desktop.vue
src/components/mobile/mobile.vue
src/components/predictive-layer/predictive-layer.vue
src/components/predictive-layer/sliding-recommendations.vue
src/design-system/tokens.scss
src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json

feat: style predictive layer

---

src/components/search/related-tags.vue

fix: align RTs with searchbox on desktop

---

package-lock.json
package.json
src/adapter/adapter.ts
src/adapter/standard-api-adapter.ts

build: update `vue`, `vue-template-compiler` and `@empathyco` dependencies

---

package-lock.json
package.json
public/index.html

EX-6651
Updates x-components version in order to support the new `XAPI` stored at `window.InterfaceX`

build(deps): update `x-components` version to 3.0.0-alpha.130

---

src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json

[EX-6744](https://searchbroker.atlassian.net/browse/EX-6744)

EX-6744 Change history queries confirmation dialog text

---

src/components/desktop/desktop-next-query-preview.vue
src/components/mobile/mobile-next-query-preview.vue
src/i18n/messages.types.ts
src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json

feat(query-preview): modify translations and styles

---

src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json
tests/e2e/cucumber/facets.feature

EX-7155
Improve texts related to My History Panel in English and Spanish
Improve how the shopper understand the feature
Se the same texts as Android App that were reviewed.

feature(history-queries): improve texts

---

src/components/results/result.vue

Change the addToCart button 
Because @javieri-empathy delete the blend-mode background color in product-card so now the button isn't visible

feature: change addToCart button to primary

---

.github/workflows/codeql.yml
src/components/scroll-to-top.vue

EX-7186
This PR basically implements in the archetype the same workflow we did for the monorepo see https://github.com/empathyco/x/pull/755
- Scan every push to main or any PR agains main in order to find potential security issues in the code.
- Weekly scan the main branch every Monday at 00:00 UTC.

ci: create codeql-analysis.yml

---

package-lock.json
package.json
src/adapter/standard-api-adapter.ts
src/components/search/facets/custom-facets.vue
tests/e2e/cucumber/sort.feature
tests/e2e/fixtures/search-response-with-banner.json
tests/e2e/fixtures/search-response-with-known-results.json
tests/e2e/fixtures/search-response-with-promoted.json

Also use facets model name in the custom facets component slots.
[EX-7259](https://searchbroker.atlassian.net/browse/EX-7259)

feat: update archetype to not use facets config

---

src/i18n/messages/index.ts
src/i18n/messages/pt.messages.json

Co-authored-by: Clara Santos <clarasantosmf@gmail.com>
Add Portuguese language to i18n texts. As @clarasantosmf did this [PR](https://github.com/empathyco/x-archetype/pull/192) but it was not finished, we are opening this one to finish it with her co-author
Add new messages file and add it to export
Cover more languages by default

feature: add portuguese language to i18n texts

---

package-lock.json
package.json
src/components/column-picker.vue
src/components/desktop/desktop-next-query-preview.vue
src/components/desktop/desktop-toolbar.vue
src/components/desktop/desktop.vue
src/components/mobile/mobile-close-aside.vue
src/components/mobile/mobile-open-aside.vue
src/components/mobile/mobile.vue
src/components/my-history/desktop-my-history-aside.vue
src/components/my-history/mobile-my-history-aside.vue
src/components/my-history/my-history-confirm-disable-modal.vue
src/components/pre-search/custom-query-preview.vue
src/components/predictive-layer/predictive-layer.vue
src/components/predictive-layer/sliding-recommendations.vue
src/components/results/result.vue
src/components/scroll-to-top.vue
src/components/search-box.vue
src/components/search/desktop-aside.vue
src/components/search/facets/selected-filters.vue
src/components/search/redirection.vue
src/components/search/related-tags.vue
src/components/search/results/mobile-partial-results.vue
src/components/search/results/partial-results.vue
src/components/search/sort.vue
src/components/search/spellcheck-message.vue
src/tailwind/plugin-options.js
tailwind.config.js

EX-5908
Add `x-button` implementation from the XDS

feat: replace x-button with XDS x-button implementation

---

src/components/desktop/desktop-toolbar.vue

[EX-7440](https://searchbroker.atlassian.net/browse/EX-7440)

feat: Show spellchecked query on results toolbar

---

src/components/results/result.vue
src/components/search/facets/price-filter-label.vue

We are forcing the format to Euros and that's not correct.
Rely on currency on the snippet instead of forcing it
We are fixing this in every customer as in here:  https://searchbroker.atlassian.net/browse/EX-7562

fix: remove forced currency format

---

cypress.json
src/components/search/results/results.vue
tests/e2e/cucumber/banner.feature
tests/e2e/cucumber/column-picker.feature
tests/e2e/cucumber/column-picker.spec.ts
tests/e2e/cucumber/facets.feature
tests/e2e/cucumber/multiple-interactions.feature
tests/e2e/cucumber/no-results.feature
tests/e2e/cucumber/predictive-components.feature
tests/e2e/cucumber/promoted.feature
tests/e2e/cucumber/results.feature
tests/e2e/cucumber/scroll.feature
tests/e2e/cucumber/scroll.spec.ts
tests/e2e/cucumber/sort.feature
tests/e2e/cucumber/spellcheck.feature
tests/e2e/cucumber/tagging.feature
tests/e2e/cucumber/url.feature

Following changes were made:
- Updated mobile viewport to iPhone X
- Fix for scroll test.
- Column-picker test now uses `'search-response-with-known-results'` fixture, preventing test from failure when there is a banner.
Tests were run using different levels of throttling

test: e2e maintenance

---

package-lock.json
package.json
src/components/desktop/desktop.vue

EX-7784
Updates archetype to vue 2.7.

build(deps): update Vue to 2.7

---

package-lock.json
package.json

chore(deps): update platform adapter

---

package-lock.json
package.json
src/components/mobile/mobile-next-query-preview.vue
src/components/pre-search/custom-query-preview.vue
src/components/predictive-layer/sliding-recommendations.vue
src/components/search/facets/selected-filters.vue
src/components/search/related-tags.vue
src/components/search/results/mobile-partial-results.vue
src/design-system/tokens.scss
tailwind.config.js

feat(design-system): use sliding panel from XDS

---

package-lock.json
package.json

[EX-7899](https://searchbroker.atlassian.net/browse/EX-7899)
To test:
- Check that now the result image has de `x-picture-image` class instead of the x-`picture__image` one.
- Placeholder & Fallback images also work properly with `x-picture-image` class
[EX-7899]: https://searchbroker.atlassian.net/browse/EX-7899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Update archetype with XDS x-picture-image class

---

package-lock.json
package.json
src/components/my-history/custom-my-history.vue
src/components/predictive-layer/predictive-layer.vue
tests/e2e/cucumber/common-steps.spec.ts
tests/e2e/cucumber/my-history.feature
tests/e2e/cucumber/my-history.spec.ts
tests/e2e/cucumber/predictive-components.spec.ts

fix: fix click on my history queries not working

---

package-lock.json
package.json
src/components/column-picker.vue
src/components/custom-header-toggle-panel.vue
src/components/desktop/desktop-toolbar.vue
src/components/desktop/desktop.vue
src/components/mobile/mobile-open-aside.vue
src/components/my-history/custom-my-history.vue
src/components/my-history/desktop-my-history-aside.vue
src/components/my-history/mobile-my-history-aside.vue
src/components/my-history/my-history-icon-bw.vue
src/components/my-history/my-history-icon.vue
src/components/my-history/no-history-icon.vue
src/components/pre-search/custom-query-preview.vue
src/components/predictive-layer/predictive-layer.vue
src/components/predictive-layer/sliding-recommendations.vue
src/components/search-box.vue
src/components/search/desktop-aside.vue
src/components/search/facets/custom-facets.vue
src/components/search/facets/custom-sliced-filters.vue
src/components/search/facets/selected-filters.vue
src/components/search/related-tags.vue
src/components/search/results/next-queries-group.vue
src/components/search/sort.vue
src/design-system/tokens.scss

[EX-7776](https://searchbroker.atlassian.net/browse/EX-7776)
* Renamed some icons to follow the naming convention `x-icon-${iconName}`
* Updated size classes
* Fix clear input btn in mobile to set it squared
[EX-7776]: https://searchbroker.atlassian.net/browse/EX-7776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Update XDS icon classes

---

package-lock.json
package.json
src/App.vue
src/components/search-box.vue
src/tailwind/plugin-options.js
tailwind.config.js

feat:(design-system): Use `input-group` from `XDS`

---

package-lock.json
package.json
src/components/desktop/desktop-toolbar.vue
src/components/mobile/mobile-open-aside.vue
src/components/mobile/mobile.vue
src/components/search/facets/facet-selected-filters.vue
tests/e2e/cucumber/multiple-interactions.feature
tests/e2e/cucumber/predictive-components.feature

The archetype designs are not updated yet, but Alicia said me to use the default badge with the auxiliary color, except in the mobile open aside button, where the lead color is used.
Keep in mind that we will use the badge in the facets headers and the filter counts, which were styled previously with independent classes.
EX-8004

feat(design-system): use xds badge

---

package-lock.json
package.json
src/components/column-picker.vue
tests/e2e/cucumber/column-picker.spec.ts

feat(design-system): use XDS button group

---

public/snippet-script.js

EX-7917
We needed to be able to get any parameter from the URL even if we don't specify it in the snippet (for testing reasons explained in the task description).
Load a query with random parameters and check that they're present in `window.initX` along with the other parameters that we're already handling from the snippet.

feature: ingest any url parameter in the snippet

---

package-lock.json
package.json
src/components/pre-search/custom-query-preview.vue
src/components/predictive-layer/predictive-layer.vue

feat: update xds button

---

src/components/pre-search/custom-query-preview.vue
src/components/results/result.vue

Add image hover
Changed result.vue component to showImageOnHover
Set a better shopper experience

feature: add image change on result hover

---

src/App.vue
src/components/desktop/desktop-toolbar.vue
src/components/desktop/desktop.vue
src/components/mobile/mobile-toolbar.vue
src/components/mobile/mobile.vue
src/components/predictive-layer/predictive-layer.vue
src/components/predictive-layer/sliding-recommendations.vue
src/components/results/custom-recommendations.vue
src/components/results/result.vue
src/components/search/facets/selected-filters.vue
src/components/search/results/partial-results.vue
src/x-components/plugin.options.ts

feat: minor style improvements

---

src/components/search/results/custom-next-query-preview.vue

[EMP-684](https://searchbroker.atlassian.net/browse/EMP-684)
[EMP-684]: https://searchbroker.atlassian.net/browse/EMP-684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: set the NQ sliding panel as the others in the archetype

---

package-lock.json
package.json
src/components/predictive-layer/full-width-predictive.vue
src/components/predictive-layer/predictive-layer.vue

[EMP-1510](https://searchbroker.atlassian.net/browse/EMP-1510)
Update x-components version to fix a bug with the x-plugin returning all the suggestions instead of just the ones that should be rendered. Then fixing the full width empathize view.
Search for something that doesn't have suggestions and then click the search bar. It shouldn't open awkwardly to an empty box.
[EMP-1510]: https://searchbroker.atlassian.net/browse/EMP-1510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update x-components to fix bug with suggestions

---

src/components/search/redirection.vue
src/i18n/messages.types.ts
src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json
src/i18n/messages/fr.messages.json
src/i18n/messages/it.messages.json
src/i18n/messages/pt.messages.json

[FLS-2657](https://searchbroker.atlassian.net/browse/FLS-2657)
Update redirection component with the translations for the new customers.
[FLS-2657]: https://searchbroker.atlassian.net/browse/FLS-2657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add translations to redirection component

---

package-lock.json
package.json

Tests performed according to [testing guidelines](https://github.com/empathyco/x/blob/main/.github/contributing/tests.md): 
[EMP-1584]: https://searchbroker.atlassian.net/browse/EMP-1584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update x-components and fix scroll bug

---

package-lock.json
package.json

Update x-components in the archetype adding a max-width to BaseRating component because if a x-flex class is applied the rating will not be filled correctly.
Add `<BaseRating :value="3"></BaseRating>` in `result.vue` file.

fix: update x-components and fix base rating component

---

src/components/my-history/my-history-aside.vue

feat: add my history location

---

package-lock.json
package.json
src/components/desktop/desktop-top-section.vue
src/components/has-scroll-past-threshold.mixin.ts
tests/e2e/cucumber/common-steps.spec.ts
tests/e2e/cucumber/scroll.feature
tests/e2e/cucumber/scroll.spec.ts

[EMP-1794] 
Tests related to this issue [EMP-1050](https://searchbroker.atlassian.net/browse/EMP-1050)
[EMP-1794]: https://searchbroker.atlassian.net/browse/EMP-1794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMP-1050]: https://searchbroker.atlassian.net/browse/EMP-1050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMP-1794]: https://searchbroker.atlassian.net/browse/EMP-1794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: test for collapse subheader when scroll down

---

package-lock.json
package.json
public/snippet-script.js
src/App.vue
src/components/has-searched.mixin.ts
src/components/pre-search/custom-query-preview.vue
src/components/search/custom-semantic-queries.vue
src/i18n/messages.types.ts
src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json
src/i18n/messages/fr.messages.json
src/i18n/messages/it.messages.json
src/i18n/messages/pt.messages.json

feat: add brand recommendations with filter and extra params

---

package-lock.json
package.json
src/components/predictive-layer/sliding-recommendations.vue
src/components/results/custom-recommendations.vue
src/components/search/custom-semantic-queries.vue
src/components/search/results/custom-next-query-preview.vue

EMP-2716
Add DisplayClickPRovider to Next Query Preview Resutls
Track this kind of carousels in the same way as topclicked recommendations and brand recommendations

feat(next-queries): add displayClick track to next queries preview

---

src/components/history-query-filters.vue
src/components/my-history/custom-my-history.vue

feat(history-queries): hide filters length in predictive

---

package-lock.json
package.json

fix(extra-params): update x-components version

---

src/i18n/messages/de.messages.json
src/i18n/messages/index.ts

json translate was added to message file

i18n message was translated into German

---

src/components/search/custom-semantic-queries.vue
src/i18n/messages/de.messages.json
src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json
src/i18n/messages/fr.messages.json
src/i18n/messages/it.messages.json
src/i18n/messages/pt.messages.json

Improve communication of semantic carousels
Feedback gathered from stakeholders that want a more explainable introductions

feat(semantics): improve no results semantics texts

---

src/components/column-picker.vue

It seems that the columns' mapping expects a value coming from a computed property. To fix it, we had added a `.value` to the `columns` property
Column picker should appear and should be reactive.
[EMP-3706]: https://searchbroker.atlassian.net/browse/EMP-3706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add .value to columns property

---

public/index.html
public/snippet-script.js
src/App.vue
src/components/pre-search/custom-query-preview.vue
src/components/predictive-layer/sliding-recommendations.vue
src/components/results/custom-recommendations.vue
src/components/results/result.vue
src/components/search/custom-semantic-queries.vue
src/components/search/results/results.vue
src/main.ts
src/shims-x-components.d.ts
src/x-components/plugin.options.ts

For the moment the goal of this PR is just to have a preview to use as playground for wysiwyg layer integration

feat: integrate wysiwyg layer

---

public/snippet-script.js

Before merging this PR, https://github.com/empathyco/wysiwyg-playground/pull/162 must be merged and populated to PRO.
- Add new conversation API in the Backroom config to active ChatWidget

feat: add conversational API configuration to backroom

---

public/snippet-script.js

Add Search URL to enable Query ranking pointing to Stage environment.

feat: Add Search URL to enable Query ranking pointing to Stage env

---

renovate.json

Use `github>empathyco/.github:frontend` https://github.com/empathyco/.github/blob/main/frontend.json config

chore(renovate): use github>empathyco/.github:frontend config

---

public/snippet-script.js

feat: safe call on wysiwyg

---

tests/e2e/cucumber/predictive-components.feature

Lately, the predictive component test has become flaky. A fix has been applied to improve reliability.

test: fix flaky predictive component e2e test

---

src/components/search/results/results.vue

feature: Prevent duplicated prompt calls

---

src/i18n/messages/de.messages.json
src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json
src/i18n/messages/fr.messages.json
src/i18n/messages/it.messages.json
src/i18n/messages/pt.messages.json

fix: RTP message: add message part

---

src/components/main.vue
src/components/related-prompts/related-prompts.vue
src/components/search/results/results.vue

fix: possible undefined property

---

tests/e2e/cucumber/scroll.spec.ts

test: do not rely on RPs to perform scroll test

---

.nvmrc
package-lock.json
package.json
src/components/desktop/desktop.vue
src/components/main.vue
src/components/mobile/mobile.vue
src/components/pre-search/pre-search-manager.vue
src/components/related-prompts/custom-related-prompts.vue
src/components/related-prompts/related-prompts.vue
src/components/search/results/custom-query-preview.vue
src/components/search/results/results.vue
src/composables/use-experience-controls.composable.ts
src/composables/use-has-scroll-past-threshold.composable.ts

refactor: update x-components and update useState usage

---

renovate.json

chore(renovate): update package update rules

---

.github/actions/cloudflare-r2/action.yaml
.github/workflows/build.yaml

fix: default deploy path

---

.github/actions/install/action.yaml
package-lock.json
package.json
src/components/column-picker.vue
src/components/history-query-filters.vue
src/components/mobile/mobile-close-aside.vue
src/components/my-history/my-history-confirm-disable-modal.vue
src/components/search/custom-semantic-queries.vue
src/components/search/desktop-aside.vue
src/components/search/facets/custom-sliced-filters.vue
src/components/search/facets/price-filter-label.vue
src/components/search/results/custom-query-preview.vue
src/composables/use-predictive-helpers.composable.ts

Add typecheck to ensure type correctness
~~blocked~~ by https://github.com/empathyco/x-archetype/pull/607

ci: add typecheck

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/actions/cloudflare-r2/action.yaml
.github/actions/cloudfront-s3/action.yaml
.github/actions/frontend-deploy/action.yaml
.github/actions/install/action.yaml
.github/workflows/build.yaml
.github/workflows/codeql.yml
.github/workflows/deploy-docker.yml
build/instrumentation.build.mjs
cypress.config.ts
docs/i18n.md
eslint.config.mjs
package.json
rollup.config.mjs
src/components/my-history/custom-my-history.vue
src/components/results/result.vue
src/components/search/facets/selected-filters.vue
src/components/search/no-results-message.vue
src/components/search/results/partial-results.vue
vite.config.mts

Homogenize lint and format checks

ci: update linting and formatting scripts

---

src/components/desktop/desktop-toolbar.vue
src/components/mobile/mobile-toolbar.vue

https://searchbroker.atlassian.net/browse/RST-4536

feat: show RT in query visualization

---

src/App.vue
src/components/search/results/next-queries-cta.vue
src/components/search/results/next-queries-tags.vue
src/components/search/results/results.vue
src/i18n/messages.types.ts
src/i18n/messages/de.messages.json
src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json
src/i18n/messages/fr.messages.json
src/i18n/messages/it.messages.json
src/i18n/messages/pt.messages.json
src/shims-x-components.d.ts

https://searchbroker.atlassian.net/browse/RST-3445

feat: add next queries cta
