src/x-components/adapter.ts

EX-4057
In order to read the new next queries from the platform API, we need to update the adapter, this PR fix this.

feat(next-queries): update adapter

---

src/App.vue

This task was originally intended to solve a problem in which PostCSS logical, a plugin that transforms logical CSS properties to physical properties and that it's run during the build, didn't create CSS fallback rules without [dir="..."] attributes.
The library doesn't support it and the creators mention it explicitly so we have to manage and add the dir attribute directly.
This task came from an issue that appeared solving a task from the Archetype issues.
Switch between ltr and rtl and check that it has effect.

feature(layout): add dir rtl to main modal

---

src/components/main.vue
src/components/toolbar.vue

Two different commits:
- main.vue: removed CSS done in the past to fix something related to the staggered fade and slide animation.
- toolbar.vue: add CollapseFromTop transition.
I forgot to put the task https://searchbroker.atlassian.net/browse/EX-4187 as the body, so please add it in the PR message.
Initially, the task describes an issue that I haven't been able to reproduce. Please, check if it happens to you but it seems that it has been fixed.
Testing it (you have to animate the sort dropdown), I noticed that something was wrong because there was a delay, pause between the start and the end of the sort animation if I use CollapseHeight. It seems to be a performance issue that doesn't happen with CollapseFromTop animation which uses scale instead of modifying the height.
Related issue …

Feature/ex 4187 the sort dropdown is overlapped 

---

build/instrumentation.build.js
public/index.html
rollup.config.js

I realised yesterday in the night that the html plugin was above the styles plugin, so it was impossible for it to detect if it had to link the CSS. After doing this, the `__EXTRACTED_CSS__` trick is no longer necessary.

build: Remove `__EXTRACTED_CSS__` in favour of html plugin order

---

.github/CODEOWNERS
.github/CODE_OF_CONDUCT.md
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md

We were missing some documentation on this repo:
Codeowners to automatically ask for review to the X Team.
Issue templates to create features and bugs.
Pull Request template, as you can see the poor layout on this PR.
Code of Conduct as we have on Interface X repository.
We should iterate on this at some point and add the Contibuting Guidelines, and maube link to the Style Guide in the X Repo, but i didnt want to open that watermelon on this PR.

docs: add issue templates and codeowners

---

build/instrumentation.build.js
package-lock.json
package.json
src/adapter/adapter.ts
src/main.ts
src/x-components/plugin.options.ts
vue.config.js

EX-5423
Removes unnecessary `polyfills` support.
Removes `app.js` facade chunk, which only contained an import to the `x-core` chunk, and renamed the entry file from `app.js` to `x-core.js`.
Install `x-components` locally building it from this [pull request](https://github.com/empathyco/x/pull/341), build the `x-archetype` and check that not `polyfills` are added in the `x-core` chunk.

build: remove `polyfills` support

---

src/App.vue
src/components/column-picker.vue
src/components/desktop/desktop-aside.vue
src/components/desktop/desktop-toolbar.vue
src/components/desktop/desktop.vue
src/components/main.vue
src/components/mobile/mobile-aside.vue
src/components/mobile/mobile.vue
src/components/predictive-layer/predictive-layer.vue
src/components/predictive-layer/sliding-recommendations.vue
src/components/results/recommendations.vue
src/components/results/result.vue
src/components/search/facets/selected-filters.vue
src/components/search/no-results-message.vue
src/components/search/related-tags.vue
src/components/search/results/next-queries-group.vue
src/components/search/results/results.vue
src/components/x-modal.vue
src/design-system/tokens.scss
src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json

feat: fix styles

---

.eslintrc
package-lock.json
package.json
src/components/column-picker.vue
src/components/desktop/desktop-toolbar.vue
src/components/main.vue
src/components/mobile/mobile-open-aside.vue
src/components/mobile/mobile-toolbar.vue
src/components/predictive-layer/predictive-layer.vue
src/components/results/recommendations.vue
src/components/search-box.vue
src/components/search/facets/selected-filters.vue
src/components/search/no-results-message.vue
src/components/search/sort.vue
src/components/search/spellcheck-message.vue
src/design-system/tokens.scss
src/i18n/messages.types.ts
src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json

fix: styles issues 

---

src/components/search/no-results-message.vue

[EX-6537](https://searchbroker.atlassian.net/browse/EX-6537)
When searching for long, single-word queries the message in the `no-results-message` component didn't wrap. This made the mobile view look really bad. This PR makes it so it would break long words and wrap.
Search for a query by smashing your keyboard a couple of times and see how the `no-results-message` looks.

fix: wrap on long words in the no results message

---

cypress.json
package-lock.json
package.json
src/components/desktop/desktop-next-query-preview.vue
src/components/mobile/mobile-next-query-preview.vue
src/components/search/results/results.vue
src/design-system/tokens.scss
src/i18n/messages.types.ts
src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json

EX-6658
Changed `components/search/results/results.vue` component used to render the results list in the grid to render a `NextQueryPreview` instead of the `NextQueriesList`.

feat: add `NextQueryPreview` carousel in results grid

---

build/instrumentation.build.js
public/snippet-script.js
src/main.ts

- Enables devtools as long as the `__enableVueDevtools__` variable is `true`. 
- Sets the `__enableVueDevtools__` in Empathy environments.
- Fixes compilation in Windows devices.

feat: enable `devtools` in Empathy environments

---

src/components/main.vue
src/components/search/index.ts
src/components/search/results/mobile-partial-results.vue
src/components/search/results/partial-results.vue
src/design-system/tokens.scss
src/i18n/messages.types.ts
src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json
src/i18n/messages/fr.messages.json

I know that some colors are not matching, cris is working on that. Right now the colors that we set in tailwind are not the same that the ones that the design has, so for example, the x-text is using neutral-10, instead of overwriting the token in the archetype what we have to do is set that value in tailwind.
What we want to achieve is that we should not override things in the archetype, everything has to be set as default in tailwind.
EX-4515

feat: add styles to partial results

---

src/components/search/facets/selected-filters.vue

EX-7431
Selected filters are tags, so they should be changed to buttons (they'll be their own component). The changes in the previous PR should be reverted.
Also, removing the custom paddings for the clear filters, the mismatch between tags and buttons sizes should be fixed with the tag component.

fix: fix styles for the selected filters reverting previous changes

---

src/components/desktop/desktop.vue
src/components/main.vue
src/components/mobile/mobile.vue

[EX-7243](https://searchbroker.atlassian.net/browse/EX-7243)
With this change we are losing the origin when clicking on the spellcheck button:
- Before:
- After:
I think that origin doesn't represent anything relevant in the case of a spellcheck, but happy to read different opinions :)

feat: Display Spellckeck above results toolbar

---

build/instrumentation.build.js

EX-7706
Sets rollup-plugin-vue `whitespace` option to `'condense'` to match the [Vue CLI defaults](https://cli.vuejs.org/migrations/migrate-from-v3.html#vue-cli-service). This should prevent empty text nodes from being generated in the output, and prevent us from having different behaviors between dev and production builds.

build: enable `whitespace: 'condense'` in `rollup-plugin-vue`

---

src/components/main.vue
tests/e2e/cucumber/no-results.feature

EX-7717
The rendering condition was wrong. Now the no-results reccommendations are correctly displayed:
Before:
After:

fix: no-results are now correctly displayed

---

src/components/my-history/custom-my-history.vue
src/i18n/messages.types.ts
src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json
src/i18n/messages/fr.messages.json
src/i18n/messages/pt.messages.json

EX-7449
Adds the results count to the MyHistory component:
Result:
[Design](https://www.figma.com/file/mYfJZHn668mGEGf61Sji6m/X-Archetype?node-id=3744%3A49475&t=PmLir2dlP89XfLcQ-0):

feat: add results count to my history

---

package-lock.json
package.json
src/components/desktop/desktop-toolbar.vue
src/components/my-history/custom-my-history.vue
src/components/search/no-results-message.vue
src/components/search/results/next-queries-group.vue
src/components/search/spellcheck-message.vue
src/i18n/messages.types.ts
src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json
src/i18n/messages/fr.messages.json
src/i18n/messages/pt.messages.json
tests/e2e/cucumber/predictive-components.feature
tests/e2e/cucumber/predictive-components.spec.ts

BREAKING CHANGE: Split `myHistory.message` translation into three different parts: `header`, `body` and `footer`.
EX-6928

feat!(i18n): replace `v-html` with `i18n` component

---

package-lock.json
package.json
src/components/predictive-layer/predictive-layer.vue
tests/e2e/cucumber/predictive-components.feature

I have moved the condition to show the predictive layer from the `Empathize` component to the `div` containing the suggestions because the `Empathize` already has some logic to hide the predictive layer if it doesn't have content.
This fixes the behaviour where the `Empathize` is not displayed after clearing a query with no results and a history queries test that was failing occasionally because the `Empathize` was closed and Cypress couldn't get the history queries elements.
EX-7720

feat(history-queries): hide history queries when there are none with results

---

src/components/column-picker.vue
src/components/search/desktop-aside.vue
src/components/search/mobile-aside.vue
src/components/search/sort.vue
src/design-system/tokens.scss
src/i18n/messages.types.ts
src/i18n/messages/es.messages.json
src/i18n/messages/pt.messages.json

EX-7275
There is some stuff in the list that was already fixed. Here is the list of things applied: 
- Change grid mobile token
- Column picker inside toolbar: differentiate selected from not selected.
- Add the identifier result’s title translation key everywhere missing
- Mobile aside & desktop aside spacings
- Sort&Filter lists spacings
Take in account: not doing anything inside predictive as there's a PR opened that will fix some stuff
[EX-7224]: https://searchbroker.atlassian.net/browse/EX-7224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(styles) Archetype recurring changes

---

.husky/pre-commit
package-lock.json
package.json

Recently `gitHooks` were failing to find `yorkie` and the commits weren't able to be performed. 
This is because that dependency was removed from `@vue/cli-plugin-typescript`.
To address it we have added `husky`, as it has more maintenance.
Developed with @mnavarroespinosa

fix: Add husky to run gitHooks

---

package-lock.json
package.json
src/components/results/result.vue
tailwind.config.js

EX-7837
- implement XDS class, 
- update packages, 
- add `backgroundColor` plugin in tailwind to support `x-picture-overlay` variant
[Sliding panel PR](https://github.com/empathyco/x-archetype/pull/246) should be merged first and then update this branch with that changes. Currently, tagging tests are failing as the row gets unstyled and then the list of products can't be scrolled as expected.
Also, the [XDS use class instead of img tag PR](https://github.com/empathyco/x/pull/1035) should be merged first and then update the package version.

feat: Implement XDS product image in archetype

---

src/components/search/custom-semantic-queries.vue
src/components/search/display-click-provider.vue

[EMP-1067](https://searchbroker.atlassian.net/browse/EMP-1067)
We need to send the tagging event of display click when a semantic query is clicked.
Search for `sofa` -> Click a semantic result -> check in the network that the event was sent with the correct payload -> search for `silla` -> Click a semantic result -> check in the network that the event was sent with the correct payload -> repeat ad infinitum -> regret your choices in life
[EMP-1067]: https://searchbroker.atlassian.net/browse/EMP-1067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: emit display click on semantic queries click

---

tests/e2e/cucumber/common-steps.spec.ts
tests/e2e/cucumber/facets.feature

Not many changes at the end. Child filters for hierarchical facets are not being returned, so test is kept as skipped until further development. 
Also, minor adjustment for `multipleinteraction` test: sometimes is was failing when looking for the result carts due to the presence of a banner.

test: review arquetype tests

---

src/components/mobile/mobile-sub-header.vue

fix: collapse header when scroll in tablet or less

---

src/components/desktop/desktop-sub-header.vue
src/components/desktop/desktop.vue
src/components/main.vue
src/components/mobile/mobile-sub-header.vue
src/components/mobile/mobile.vue

Results grid have to be visible even if there is a redirection. I just deleted the v-if that checked if there was a redirection.
Manually checked that the results grid was displayed now even if there is a redirection

fix(search): Products grid is shown even if there's a redirection

---

package-lock.json
package.json
public/snippet-script.js

Currently, when we use the live env, we can't define it as an empty string ('') because the request will fail, it will put two . one after the other. This doesn't make much sense. We have fixed this problem in the X project, and now we have to update X in the archetype.
Add in the URL `env=live`.
[EMP-1625]: https://searchbroker.atlassian.net/browse/EMP-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update archetype with X project

---

src/components/predictive-layer/full-width-predictive.vue

Currently full predictive layer is open when there are no suggestions to display. Maybe in the archetype looks good but in several customers we have to change it each time.
Search for a query with no suggestions, for example: `print midi dress women`
[EMP-1642]: https://searchbroker.atlassian.net/browse/EMP-1642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: hide full empathize when there are no suggestions

---

build/instrumentation.build.js

Public files where copied to `dist` regardless of the actual output directory in the build. This PR changes it to take the actual directory.
Change the output and run the build, favicon and snippet config file should be in the actual output directory.

feat: better output directory for public files in build

---

src/components/desktop/desktop.vue
src/components/mobile/mobile.vue
src/components/search/fallback-disclaimer-message.vue
src/components/search/index.ts
src/components/search/no-results-message.vue
src/components/search/spellcheck-message.vue
src/i18n/messages.types.ts
src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json
src/i18n/messages/fr.messages.json
src/i18n/messages/it.messages.json
src/i18n/messages/pt.messages.json
src/tailwind/plugin-options.js

EMP-2097
We wanted to add de fallback disclaimer component to the archetype.
Also, in this PR I have extracted the stylings of the messages to a component class and added translations.
No tests were created for this because the feature depends heavily on the behaviour of the endpoint and it not being mocked makes the tests too flakey.
Search for `sneaker high-top` -> Add filter `Gender>Unisex` -> Search for `sneaker high-top pink` -> The message should appear.

feat: add fallback disclaimer for removing filters

---

renovate.json

This PR prevents renovate from updating x related dependencies.

chore: exclude x deps from renovate

---

src/adapter/adapter.ts

EMP-2720
Remove explicit override of the experience control URL
The experience control endpoint has been deployed in Staging environment, so we no longer need the override.
https://api.staging.empathy.co/config/v1/public/configs?service=xcontrols&instance=empathy
Note: This will not work from  PR preview, as the sudomain is x.test.empathy.co and the experience control ingress in Staging only accepts subdomain x.staging.empathy.co or localhost:8080
Run it locally to test.
To have a standard implementation

fix: update experience control endpoint

---

src/components/pre-search/custom-query-preview.vue
src/tailwind/plugin-options.js

EMP-2492
When opening Empathize without query, and then closing it by clicking somewhere in the brand recommendations area, the carousel behind the Empathize stays hidden until you roll over it.
Google Chrome has a problem rendering components with `mask` style applied. We think that is a new bug from Chrome, so we have decided to develop a temporary solution and wait for them to fix it soon.
Next steps: 
- Apply this fix to all the setups with a fill width empathize.
Go to the archetype:
- Open empathize
- Click somewhere in the brand recommendations area
The carousel that was behind the empathize should look ok.
[EMP-2492]: https://searchbroker.atlassian.net/browse/EMP-2492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: rendering problem in query preview sliding panel

---

src/components/predictive-layer/full-width-predictive.vue

If condition changed to enable showing SKU although no other predictive layer items are available

fix: Show SKU on desktop

---

public/snippet-script.js
src/App.vue
src/adapter/adapter.ts
src/components/column-picker.vue
src/components/search/custom-semantic-queries.vue
src/components/search/results/custom-next-query-preview.vue
src/components/search/results/results.vue
src/composables/use-experience-controls.composable.ts
src/composables/use-store.composable.ts

Use XControls to config:
- The `maxNextQueriesPerGroup` to be shown
- Column options to display for desktop
**Test with `dress` and `useXControls` composable inside `custom-query-preview.vue` component to quickly see the changes** ([you can check this commit to do so](https://github.com/empathyco/x-archetype/pull/360/commits/9e8cd12e4f9ae654ebd46401bfdaac28acf2d512))

feat: Use XControls in NextQueries and Layout

---

.github/workflows/pull-request.yml

[OPS-8556]
Same motivation than https://github.com/empathyco/x/pull/1320
Replace usage of Personal Access Token with automatic repo scoped token.
[OPS-8556]: https://searchbroker.atlassian.net/browse/OPS-8556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Replace usage of SUPPORT_TOKEN PAT

---

src/components/search/results/results.vue

When a user types a query that has no results, the promoteds or banners configured for that query are not displayed in the frontend.
The search service is still returning them in the API response, but the frontend is not displaying them.
Find a query where the search response returns no results and banners or promoted. 
[EMP-3022]: https://searchbroker.atlassian.net/browse/EMP-3022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: make banners and promoted appear without results

---

package-lock.json
package.json

Recently we discovered an issue with the dynamic chunks being loaded all at once instead of lazy. This is related to an issue on the latest version for [rollup-plugin-generate-html-template ](https://github.com/bengsfort/rollup-plugin-generate-html-template/issues/34).
This PR makes the version stick to previous one until the issue is solved.

fix: lazy loading chunks

---

src/components/mobile/mobile.vue
src/components/predictive-layer/predictive-popular-searches.vue

[EMP-3460](https://searchbroker.atlassian.net/browse/EMP-3460)
Currently in the archetype for mobile devices, the query previews are shown in the pre-search state. However, once you focus on the search box there is no way to go back and see the query previews since the empathize is always taking the full height of the device.
Changes (only mobile): 
- Removed the `x-layout-stack` class when there is no query, so query previews are still shown below the predictive layer & user can scroll to its content.
- Add spacing below the predictive layer, so the spacing between it & query previews is consistent (visually we have the same space between predictive as the one between each queries preview carousel). 
- Add the `x-mt-8` in popular searches: this was sometimes a recurring change in setups, …

Change empathize layout for mobile devices

---

src/components/pre-search/custom-query-preview.vue
src/components/search/display-click-provider.vue

Sends the correct origin in the query event and in the search request. That means sending in the QueryPreviewList the queryFeature 'customer' .
Also, we have to send the click and the display events. Take a look to the DisplayClickProvider component.
1. Review the search request of the queries preview and the `origin` field should appear.
2. Go to `Network` in the devTools and when you click on a queryPreview result, click and displayClick should be sent.
[EMP-3537]: https://searchbroker.atlassian.net/browse/EMP-3537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add click event and queryFeature in queriesPreview

---

package-lock.json
package.json
src/components/pre-search/custom-query-preview.vue
src/components/search/display-click-provider.vue

Update the Archetype project with the last version of `x-components` and with the approach of track query when a result of a QueryPreview is clicked.
Open the devTools and go to the Network option. Click on a result of a QueryPreview and check if click, displayClick and query are sent.
[EMP-3538]: https://searchbroker.atlassian.net/browse/EMP-3538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: track query when a result of a QP is clicked

---

src/components/predictive-layer/predictive-layer.vue

When we use the floating predictive and autoFocus of the searchBox there is a bug when you open X for the first time, the empathize doesn't open. 
To test it, you have to use the `DesktopHeaderFloatingPredictive` component in the `desktop-top-section` file and set the `autoFocus` property in the `searchBox` component to `true`.
[EMP-3649]: https://searchbroker.atlassian.net/browse/EMP-3649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: open empathize with autoFocus true

---

src/components/search/results/custom-next-query-preview.vue

We were wrapping the value of a computed property (queryGetter) inside of another computed property (query).
To test it, you can use env=live and:
1)query=shoulder bag
2)query=shoulder + relatedTag=bag
3)query=shoulder + relatedTag=bag + relatedTag=velvet

fix: remove redundant use of computed in query

---

.github/workflows/deploy-docker.yml

build: publish docker image on push to main

---

src/adapter/docker.adapter.ts

Because of resources, we need to use the data bot in production environment to generate the data for SMC, so now we will consume those endpoints
I have changed the hardcoded URLs for related tags and next queries to use production endpoints (already working) instead of staging endpoints.
The motivation was that we needed the bot to be able to consume more resources so he could ingest our feed. Instead of changing it for all staging clients, we will use the instance on production environment as that one already has the needed resources.
I have already tested the endpoints. They contain information in the same format as staging and the URLs I wrote are correct

Using RT and NQ Production Endpoints for SMC

---

package-lock.json
package.json
src/App.vue

From the Backroom team, we need the archetype to support reload search programmatically to *refresh* the search when a product is boosted or buried from it.
- Update X dependencies
- Add WYSIWYG reload search listener (min version required @empathy/x-components@5.0.0-alpha.46)

feat: add wysiwyg reload search functionality

---

src/App.vue
src/main.ts

When available the spellchecked query must be sent to Backroom instead of the written one so tooling can be properly applied to the displayed results.
- [xx] I have performed a **self-review** on my own code.

fix: Send spellchecked query to Backroom

---

public/snippet-script.js
src/App.vue

We have a bug in Backroom in which if after performing a query the user logs in, when returning to the Search layer Backroom context is not updated.
This is because the Backroom context was only updated with the `SearchRequestChanged`event but that event is not fired in the first search if loaded from the URL; adding a single line on the `ParamsLoadedFromUrl` fixes the issue.

fix: Fix backroom back from login context issue

---

.github/actions/install/action.yaml
.github/workflows/build.yaml
.github/workflows/deploy-docker.yml
.github/workflows/pull-request.yml

This pull request updates the Node.js version used in various GitHub Actions workflows from version 18 to version 22. The most important changes are as follows:
Updates to Node.js version:
* [`.github/actions/install/action.yaml`](diffhunk://#diff-1c50054d5c05df1fa07c9f0853b2f3673d3d993d74a7bdbd2b46f9845acc6f65L9-R9): Updated `node-version` from '18' to '22' in the `steps` section.
* [`.github/workflows/build.yaml`](diffhunk://#diff-d0777657fa3fd81d23aaf7273e58aee453b04e67882517900c56daeef9b3e4c1L17-R17): Updated `node-version` from '18' to '22' in the `jobs` section.
* [`.github/workflows/deploy-docker.yml`](diffhunk://#diff-04ec4378b9f42e59c8776517c7b3c7eeacdde33056482e31a85d41d7439101a1L28-R28): Updated `node-version` from '18' to '22' in the `jobs` section.
* …

ci: bump node version to 22

---

package-lock.json
src/components/related-prompts/custom-related-prompts.vue
src/components/related-prompts/related-prompts-tag-list.vue
src/components/search/results/results.vue

Refactor the `RelatedPromptTagList` component to remove the list of next queries inside the prompt tag. With these changes when selecting a prompt, we will show all the previews of the associated next queries.

refactor: remove next queries from related prompt tag

---

package-lock.json
src/components/desktop/desktop.vue
src/components/main.vue
src/components/mobile/mobile.vue
src/components/related-prompts/custom-related-prompts.vue
src/components/related-prompts/related-prompts-tag-list.vue
src/i18n/messages.types.ts
src/i18n/messages/de.messages.json
src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json
src/i18n/messages/fr.messages.json
src/i18n/messages/it.messages.json
src/i18n/messages/pt.messages.json

feature: Fix RPs layout for mobile devices

---

src/components/desktop/desktop-toolbar.vue
src/components/mobile/mobile-close-aside.vue
src/components/mobile/mobile-open-aside.vue
src/components/mobile/mobile-toolbar.vue
src/components/my-history/custom-my-history.vue
src/components/my-history/my-history-aside.vue
src/components/predictive-layer/full-width-predictive.vue
src/components/predictive-layer/predictive-layer.vue
src/components/results/result.vue
src/components/search/desktop-aside.vue
src/components/search/facets/selected-filters.vue
src/components/search/fallback-disclaimer-message.vue
src/components/search/results/custom-next-query-preview.vue
src/components/search/spellcheck-message.vue
src/i18n/messages/de.messages.json
src/i18n/messages/en.messages.json
src/i18n/messages/es.messages.json
src/i18n/messages/fr.messages.json
src/i18n/messages/it.messages.json
src/i18n/messages/pt.messages.json

[RST-3983](https://searchbroker.atlassian.net/browse/RST-3983)
[RST-3983]: https://searchbroker.atlassian.net/browse/RST-3983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
**Take into account:** 
In vue-i18n v9, when you use pluralization, the count you pass as the second argument is not automatically available for interpolation unless your placeholder is named {count}. So, some placeholders have been renamed to work properly.

feat: improve i18n implementation

---

src/composables/use-environment.composable.ts
src/composables/use-feature-flags.composable.ts

This new composable lets us toggle features on and off. Here's what it does:
- Makes it super easy to hide or show features based on simple flags
- Uses TypeScript to catch typos and give nice auto-completion
- Keeps all feature flags in one place for easy management
- Allows merging to main when a feature is done, and performs releases containing no executable code.
Use example:
```
import { FeatureFlag, useFeatureFlags } from '../composables/use-feature-flags.composable';
const { isFeatureEnabled } = useFeatureFlags();
const teleportFeature = isFeatureEnabled(FeatureFlag.TELEPORT_FEATURE);
```

feat: add feature flag composable
